-- Sample Company Users for Firmalar Page
-- Insert sample architectural companies

INSERT INTO users (email, password_hash, first_name, last_name, company_name, user_type, profession, phone, location, website, bio, avatar_url, specializations, experience_years, is_verified, is_active, subscription_type, created_at, updated_at)
VALUES 
  (
    'info@yilmazmimari.com',
    '$2b$10$dummy.hash.for.sample.data.only',
    'Ahmet',
    'Yılmaz',
    'Yılmaz Mimarlık',
    'company',
    'Mimar',
    '+90 212 555 0123',
    'İstanbul',
    'www.yilmazmimari.com',
    'Modern ve sürdürülebilir mimari çözümler sunan deneyimli ekibimizle, konut ve ticari projelerinizi hayata geçiriyoruz. 2010 yılından bu yana sektörde faaliyet göstermekteyiz.',
    'https://images.pexels.com/photos/1222271/pexels-photo-1222271.jpeg?auto=compress&cs=tinysrgb&w=150',
    'Konut Projeleri,Ticari Mimari,İç Mimari,Sürdürülebilir Tasarım',
    14,
    true,
    true,
    'professional',
    NOW(),
    NOW()
  ),
  (
    'info@karamimari.com',
    '$2b$10$dummy.hash.for.sample.data.only',
    'Zeynep',
    'Kara',
    'Kara Mimarlık Atölyesi',
    'company',
    'Mimar',
    '+90 312 555 0456',
    'Ankara',
    'www.karamimari.com',
    'Yaratıcı ve yenilikçi tasarım anlayışımızla, her projeye özgün çözümler üretiyoruz. Villa tasarımı ve restorasyon konularında uzmanız.',
    'https://images.pexels.com/photos/1239291/pexels-photo-1239291.jpeg?auto=compress&cs=tinysrgb&w=150',
    'Villa Tasarımı,Restorasyon,Peyzaj Mimarlığı,Konsept Tasarım',
    9,
    true,
    true,
    'professional',
    NOW(),
    NOW()
  ),
  (
    'info@ozkanmimari.com',
    '$2b$10$dummy.hash.for.sample.data.only',
    'Mehmet',
    'Özkan',
    'Özkan Mimarlık',
    'company',
    'Mimar',
    '+90 232 555 0789',
    'İzmir',
    'www.ozkanmimari.com',
    'Minimalist ve fonksiyonel tasarım prensipleriyle, çağdaş yaşam alanları yaratıyoruz. Ofis ve konut projelerinde uzmanlaşmış bir ekibiz.',
    'https://images.pexels.com/photos/91227/pexels-photo-91227.jpeg?auto=compress&cs=tinysrgb&w=150',
    'Minimalist Tasarım,Ofis Projeleri,Konut Kompleksleri,Urban Tasarım',
    6,
    true,
    true,
    'basic',
    NOW(),
    NOW()
  ),
  (
    'info@studioarch.com',
    '$2b$10$dummy.hash.for.sample.data.only',
    'Can',
    'Demir',
    'Studio Arch',
    'company',
    'Mimar',
    '+90 212 555 0987',
    'İstanbul',
    'www.studioarch.com',
    'Uluslararası standartlarda projeler üreten, ödüllü mimarlık stüdyosu. Kurumsal projeler, AVM ve otel tasarımlarında lider konumdayız.',
    'https://images.pexels.com/photos/2379004/pexels-photo-2379004.jpeg?auto=compress&cs=tinysrgb&w=150',
    'Kurumsal Projeler,AVM,Otel,Master Plan',
    12,
    true,
    true,
    'enterprise',
    NOW(),
    NOW()
  ),
  (
    'info@anadolumimari.com',
    '$2b$10$dummy.hash.for.sample.data.only',
    'Elif',
    'Şahin',
    'Anadolu Mimarlık',
    'company',
    'Mimar',
    '+90 322 555 1234',
    'Bursa',
    'www.anadolumimari.com',
    'Geleneksel Anadolu mimarisini modern çizgilerle buluşturan projeler üretiyoruz. Butik otel ve villa projelerinde öncü bir firmayız.',
    'https://images.pexels.com/photos/774909/pexels-photo-774909.jpeg?auto=compress&cs=tinysrgb&w=150',
    'Butik Otel,Villa,Geleneksel Mimari,Restorasyon',
    8,
    true,
    true,
    'professional',
    NOW(),
    NOW()
  ),
  (
    'info@akdenizmimari.com',
    '$2b$10$dummy.hash.for.sample.data.only',
    'Ali',
    'Yıldız',
    'Akdeniz Mimarlık',
    'company',
    'Mimar',
    '+90 242 555 5678',
    'Antalya',
    'www.akdenizmimari.com',
    'Akdeniz iklimi ve yaşam tarzına uygun projeler tasarlıyoruz. Turizm tesisleri ve yazlık konut projelerinde deneyimliyiz.',
    'https://images.pexels.com/photos/1043474/pexels-photo-1043474.jpeg?auto=compress&cs=tinysrgb&w=150',
    'Turizm Tesisleri,Yazlık Konut,Peyzaj,Sürdürülebilir Mimari',
    10,
    true,
    true,
    'professional',
    NOW(),
    NOW()
  )
ON CONFLICT (email) DO NOTHING;
